-- MySQL Script generated by MySQL Workbench
-- Fri Jun 18 08:00:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Prueba2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Prueba2` ;

-- -----------------------------------------------------
-- Schema Prueba2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Prueba2` DEFAULT CHARACTER SET utf8 ;
USE `Prueba2` ;

-- -----------------------------------------------------
-- Table `Prueba2`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prueba2`.`cliente` ;

CREATE TABLE IF NOT EXISTS `Prueba2`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prueba2`.`orden`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prueba2`.`orden` ;

CREATE TABLE IF NOT EXISTS `Prueba2`.`orden` (
  `idOrden` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `direccionDespacho` VARCHAR(45) NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idOrden`),
  INDEX `fk_orden_cliente_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_orden_cliente`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `Prueba2`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prueba2`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prueba2`.`autor` ;

CREATE TABLE IF NOT EXISTS `Prueba2`.`autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prueba2`.`libro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prueba2`.`libro` ;

CREATE TABLE IF NOT EXISTS `Prueba2`.`libro` (
  `idLibro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(80) NOT NULL,
  `añoPublicacion` INT NULL,
  `editorial` VARCHAR(45) NULL,
  `precioActual` INT NOT NULL,
  `stock` INT NOT NULL,
  `autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`idLibro`),
  INDEX `fk_libro_autor1_idx` (`autor_idAutor` ASC),
  CONSTRAINT `fk_libro_autor1`
    FOREIGN KEY (`autor_idAutor`)
    REFERENCES `Prueba2`.`autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prueba2`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prueba2`.`item` ;

CREATE TABLE IF NOT EXISTS `Prueba2`.`item` (
  `orden_idOrden` INT NOT NULL,
  `libro_idLibro` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` INT NOT NULL,
  PRIMARY KEY (`orden_idOrden`, `libro_idLibro`),
  INDEX `fk_item_orden1_idx` (`orden_idOrden` ASC),
  INDEX `fk_item_libro1_idx` (`libro_idLibro` ASC),
  CONSTRAINT `fk_item_orden1`
    FOREIGN KEY (`orden_idOrden`)
    REFERENCES `Prueba2`.`orden` (`idOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_libro1`
    FOREIGN KEY (`libro_idLibro`)
    REFERENCES `Prueba2`.`libro` (`idLibro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;