-- MySQL Script generated by MySQL Workbench
-- Wed Jun 23 18:12:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendaDeVideojuegos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendaDeVideojuegos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendaDeVideojuegos` DEFAULT CHARACTER SET utf8 ;
USE `tiendaDeVideojuegos` ;

-- -----------------------------------------------------
-- Table `tiendaDeVideojuegos`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaDeVideojuegos`.`proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `dirección` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaDeVideojuegos`.`ordenProveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaDeVideojuegos`.`ordenProveedor` (
  `idOrden` INT NOT NULL AUTO_INCREMENT,
  `proveedor_idProveedor` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idOrden`),
  INDEX `fk_ordenProveedor_proveedor_idx` (`proveedor_idProveedor` ASC),
  CONSTRAINT `fk_ordenProveedor_proveedor`
    FOREIGN KEY (`proveedor_idProveedor`)
    REFERENCES `tiendaDeVideojuegos`.`proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaDeVideojuegos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaDeVideojuegos`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `dirección` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaDeVideojuegos`.`ordenCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaDeVideojuegos`.`ordenCliente` (
  `idOrdenCliente` INT NOT NULL AUTO_INCREMENT,
  `cliente_idCliente` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrdenCliente`),
  INDEX `fk_ordenCliente_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_ordenCliente_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `tiendaDeVideojuegos`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaDeVideojuegos`.`videojuego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaDeVideojuegos`.`videojuego` (
  `idVideojuego` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `plataforma` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `precioActual` INT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`idVideojuego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaDeVideojuegos`.`itemOrdenCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaDeVideojuegos`.`itemOrdenCliente` (
  `ordenCliente_idOrdenCliente` INT NOT NULL,
  `videojuego_idVideojuego` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  INDEX `fk_item_ordenCliente1_idx` (`ordenCliente_idOrdenCliente` ASC),
  PRIMARY KEY (`ordenCliente_idOrdenCliente`, `videojuego_idVideojuego`),
  INDEX `fk_item_videojuego1_idx` (`videojuego_idVideojuego` ASC),
  CONSTRAINT `fk_item_ordenCliente1`
    FOREIGN KEY (`ordenCliente_idOrdenCliente`)
    REFERENCES `tiendaDeVideojuegos`.`ordenCliente` (`idOrdenCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_videojuego1`
    FOREIGN KEY (`videojuego_idVideojuego`)
    REFERENCES `tiendaDeVideojuegos`.`videojuego` (`idVideojuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tiendaDeVideojuegos`.`itemOrdenProveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendaDeVideojuegos`.`itemOrdenProveedor` (
  `ordenProveedor_idOrden` INT NOT NULL,
  `videojuego_idVideojuego` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  INDEX `fk_item_ordenProveedor1_idx` (`ordenProveedor_idOrden` ASC),
  PRIMARY KEY (`ordenProveedor_idOrden`, `videojuego_idVideojuego`),
  INDEX `fk_item_videojuego1_idx` (`videojuego_idVideojuego` ASC),
  CONSTRAINT `fk_item_ordenProveedor10`
    FOREIGN KEY (`ordenProveedor_idOrden`)
    REFERENCES `tiendaDeVideojuegos`.`ordenProveedor` (`idOrden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_videojuego10`
    FOREIGN KEY (`videojuego_idVideojuego`)
    REFERENCES `tiendaDeVideojuegos`.`videojuego` (`idVideojuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
