-- MySQL Script generated by MySQL Workbench
-- Thu Jun 24 10:28:07 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema unidad_educativa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unidad_educativa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unidad_educativa` DEFAULT CHARACTER SET utf8 ;
USE `unidad_educativa` ;

-- -----------------------------------------------------
-- Table `unidad_educativa`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad_educativa`.`carrera` (
  `idCarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `descripcion` TEXT NULL,
  `carreracol` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad_educativa`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad_educativa`.`semestre` (
  `idSemestre` INT NOT NULL AUTO_INCREMENT,
  `nroSemestre` INT NULL,
  `carrera_idCarrera` INT NOT NULL,
  PRIMARY KEY (`idSemestre`),
  INDEX `fk_semestre_carrera_idx` (`carrera_idCarrera` ASC),
  CONSTRAINT `fk_semestre_carrera`
    FOREIGN KEY (`carrera_idCarrera`)
    REFERENCES `unidad_educativa`.`carrera` (`idCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad_educativa`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad_educativa`.`asignatura` (
  `idAsignatura` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `semestre_idSemestre` INT NOT NULL,
  PRIMARY KEY (`idAsignatura`),
  INDEX `fk_asignatura_semestre1_idx` (`semestre_idSemestre` ASC),
  CONSTRAINT `fk_asignatura_semestre1`
    FOREIGN KEY (`semestre_idSemestre`)
    REFERENCES `unidad_educativa`.`semestre` (`idSemestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad_educativa`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad_educativa`.`docente` (
  `idDocente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NULL,
  PRIMARY KEY (`idDocente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad_educativa`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad_educativa`.`estudiante` (
  `idEstudiante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NULL,
  PRIMARY KEY (`idEstudiante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad_educativa`.`evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad_educativa`.`evaluacion` (
  `idEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `asignatura_idAsignatura` INT NOT NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`idEvaluacion`),
  INDEX `fk_evaluacion_asignatura1_idx` (`asignatura_idAsignatura` ASC),
  CONSTRAINT `fk_evaluacion_asignatura1`
    FOREIGN KEY (`asignatura_idAsignatura`)
    REFERENCES `unidad_educativa`.`asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad_educativa`.`asignatura_has_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad_educativa`.`asignatura_has_docente` (
  `asignatura_idAsignatura` INT NOT NULL,
  `docente_idDocente` INT NOT NULL,
  PRIMARY KEY (`asignatura_idAsignatura`, `docente_idDocente`),
  INDEX `fk_asignatura_has_docente_docente1_idx` (`docente_idDocente` ASC),
  CONSTRAINT `fk_asignatura_has_docente_asignatura1`
    FOREIGN KEY (`asignatura_idAsignatura`)
    REFERENCES `unidad_educativa`.`asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_has_docente_docente1`
    FOREIGN KEY (`docente_idDocente`)
    REFERENCES `unidad_educativa`.`docente` (`idDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad_educativa`.`asignatura_has_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad_educativa`.`asignatura_has_estudiante` (
  `asignatura_idAsignatura` INT NOT NULL,
  `estudiante_idEstudiante` INT NOT NULL,
  PRIMARY KEY (`asignatura_idAsignatura`, `estudiante_idEstudiante`),
  INDEX `fk_asignatura_has_estudiante_estudiante1_idx` (`estudiante_idEstudiante` ASC),
  INDEX `fk_asignatura_has_estudiante_asignatura1_idx` (`asignatura_idAsignatura` ASC),
  CONSTRAINT `fk_asignatura_has_estudiante_asignatura1`
    FOREIGN KEY (`asignatura_idAsignatura`)
    REFERENCES `unidad_educativa`.`asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_has_estudiante_estudiante1`
    FOREIGN KEY (`estudiante_idEstudiante`)
    REFERENCES `unidad_educativa`.`estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unidad_educativa`.`estudiante_has_evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unidad_educativa`.`estudiante_has_evaluacion` (
  `estudiante_idEstudiante` INT NOT NULL,
  `evaluacion_idEvaluacion` INT NOT NULL,
  `nota` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`estudiante_idEstudiante`, `evaluacion_idEvaluacion`),
  INDEX `fk_estudiante_has_evaluacion_evaluacion1_idx` (`evaluacion_idEvaluacion` ASC),
  INDEX `fk_estudiante_has_evaluacion_estudiante1_idx` (`estudiante_idEstudiante` ASC),
  CONSTRAINT `fk_estudiante_has_evaluacion_estudiante1`
    FOREIGN KEY (`estudiante_idEstudiante`)
    REFERENCES `unidad_educativa`.`estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_has_evaluacion_evaluacion1`
    FOREIGN KEY (`evaluacion_idEvaluacion`)
    REFERENCES `unidad_educativa`.`evaluacion` (`idEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
